import { z } from 'zod';

export const parkSchema = z.enum(['L', 'S']);
export const mapParkSchema = z.enum(['L', 'S', 'both']);
export const imageKeySchema = z.string().min(1).nullable();
export const pageSchema = z.coerce.number().int().positive().default(1);
export const paginationSchema = <T extends z.ZodTypeAny>(item: T) => z.object({ nextUrl: z.string().nullable(), previousUrl: z.string().nullable(), totalRecords: z.number().int().nonnegative(), totalPages: z.number().int().nonnegative(), currentPage: z.number().int().positive(), startIndex: z.number().int().nonnegative(), endIndex: z.number().int().nonnegative(), results: z.array(item) });
export const errorSchema = z.object({ detail: z.string().optional(), non_field_errors: z.array(z.string()).optional() }).passthrough();
export const userSchema = z.object({ userId: z.number().int().positive(), email: z.string().email().optional(), nickname: z.string().min(1).max(20), icon: z.string().nullable(), isSocialAccount: z.boolean().optional(), url: z.string().nullable() });
export const publicUserSchema = userSchema.pick({ userId: true, nickname: true, icon: true, url: true });
export const markerSchema = z.object({ markerId: z.number().int().positive(), lat: z.number(), lng: z.number(), park: parkSchema, numberOfPublicArticles: z.object({ total: z.number().int().nonnegative(), eachCategory: z.array(z.number().int().nonnegative()).length(7) }), areaNames: z.array(z.string()).optional() });
export const articlePreviewSchema = z.object({ postId: z.number().int().positive(), title: z.string(), image: z.string().nullable(), category: z.number().int().min(0).max(6), createdAt: z.string(), numberOfGoods: z.number().int().nonnegative() });
export const articleSchema = z.object({ postId: z.number().int().positive(), title: z.string().min(1).max(100), description: z.string(), marker: z.union([z.number().int().positive(), markerSchema]), category: z.number().int().min(0).max(6), image: z.string().nullable(), isDraft: z.boolean(), author: z.union([z.number().int().positive(), publicUserSchema]), createdAt: z.string(), updatedAt: z.string(), numberOfGoods: z.number().int().nonnegative().optional(), haveAddedGood: z.boolean().optional() });
export const articleWriteSchema = z.object({ title: z.string().min(1).max(100), description: z.string().min(1), marker: z.number().int().positive(), category: z.coerce.number().int().min(0).max(6), isDraft: z.coerce.boolean(), image: imageKeySchema.optional() });
export const specialMapSchema = z.object({ specialMapId: z.number().int().positive(), author: z.union([z.number().int().positive(), publicUserSchema]), title: z.string().min(1).max(100), thumbnail: z.string().nullable(), isPublic: z.boolean(), description: z.string(), selectablePark: mapParkSchema, minLatitude: z.number(), maxLatitude: z.number(), minLongitude: z.number(), maxLongitude: z.number(), createdAt: z.string().optional() });
export const specialMapWriteSchema = specialMapSchema.omit({ specialMapId: true, author: true, createdAt: true }).partial({ thumbnail: true, minLatitude: true, maxLatitude: true, minLongitude: true, maxLongitude: true });
export const specialMapMarkerSchema = z.object({ specialMapMarkerId: z.number().int().positive(), specialMap: z.number().int().positive(), lat: z.number(), lng: z.number(), park: parkSchema, image: z.string().nullable(), description: z.string(), variant: z.string().min(1).max(15) });
export const specialMapMarkerWriteSchema = specialMapMarkerSchema.omit({ specialMapMarkerId: true, specialMap: true });
export const registrationSchema = z.object({ email: z.string().email(), nickname: z.string().min(1).max(20), password1: z.string().min(8), password2: z.string().min(8) }).refine((value) => value.password1 === value.password2, { path: ['password2'], message: 'パスワードが一致しません。' });
export const loginSchema = z.object({ email: z.string().email(), password: z.string().min(1) });
export const inquirySchema = z.object({ email: z.string().email(), tag: z.string().max(100), name: z.string().min(1).max(20), message: z.string().min(1).max(5000) });
export type User = z.infer<typeof userSchema>;
export type Article = z.infer<typeof articleSchema>;
export type Marker = z.infer<typeof markerSchema>;
export type SpecialMap = z.infer<typeof specialMapSchema>;
export type SpecialMapMarker = z.infer<typeof specialMapMarkerSchema>;
