export const PAGE_NAMES = {
  login: 'ログイン',
  signup: 'アカウント作成',
  admin: 'マイページ',
  myArticles: 'マイ投稿一覧',
  accountSettings: 'アカウント管理',
  profileEdit: 'プロフィール変更',
  passwordChange: 'パスワード変更',
  deactivateAccount: 'アカウント削除',
  articles: '投稿一覧＆検索',
  passwordInitialize: 'パスワード初期化',
  verifyEmail: 'メールアドレス確認',
  notFound: 'Page not found',
  internalError: 'Internal server error',
  inquiry: 'お問い合わせ',
  policy: 'プライバシーポリシー',
};
